name: bevfusion
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - magma-cuda113=2.5.2=1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.10.1=py38_cu113
  - typing_extensions=4.9.0=py38h06a4308_1
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - babel==2.14.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - black==24.4.0
    - bleach==6.1.0
    - blinker==1.7.0
    - boto3==1.34.151
    - botocore==1.34.151
    - certifi==2024.2.2
    - cffi==1.16.0
    - chardet==4.0.0
    - charset-normalizer==3.3.2
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==3.0.11
    - dash==2.16.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - descartes==1.1.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - filetype==1.2.0
    - fire==0.6.0
    - flake8==7.0.0
    - flask==3.0.3
    - fonttools==4.51.0
    - fqdn==1.5.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.29.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.62.1
    - h5py==3.11.0
    - idna==3.7
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - install==1.3.5
    - ipykernel==6.29.4
    - ipython==8.12.3
    - ipywidgets==8.1.2
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - jmespath==1.0.1
    - joblib==1.4.0
    - json5==0.9.25
    - jupyter==1.0.0
    - jupyter-client==8.6.1
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.6
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.26.0
    - jupyterlab-widgets==3.0.10
    - kiwisolver==1.4.5
    - llvmlite==0.41.1
    - loguru==0.7.2
    - lyft-dataset-sdk==0.0.8
    - markdown==3.6
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.7
    - mccabe==0.7.0
    - mistune==3.0.2
    - mmcv==1.5.0
    - mmcv-full==1.5.0
    - mmdet==2.20.0
    - mmengine==0.10.3
    - mpi4py==3.0.3
    - msgpack==1.0.8
    - msgpack-numpy==0.4.8
    - multimethod==1.10
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.1
    - notebook==7.1.3
    - notebook-shim==0.2.4
    - numba==0.58.1
    - numpy==1.24.4
    - nuscenes-devkit==1.1.9
    - nvidia-nccl-cu12==2.19.3
    - oauthlib==3.2.2
    - open3d==0.18.0
    - opencv-python-headless==4.10.0.84
    - overrides==7.7.0
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==10.4.0
    - plotly==5.21.0
    - plyfile==1.0.3
    - prefetch-generator==1.0.3
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - protobuf==5.26.1
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pybboxes==0.1.6
    - pycocotools==2.0.7
    - pycodestyle==2.11.1
    - pycparser==2.22
    - pyflakes==3.2.0
    - pyparsing==3.1.2
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==26.0.0
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - roboflow==1.1.37
    - rsa==4.9
    - s3transfer==0.10.2
    - sahi==0.11.18
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - seaborn==0.13.2
    - send2trash==1.8.3
    - setuptools==72.1.0
    - shapely==1.8.5.post1
    - six==1.16.0
    - smmap==5.0.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - tensorpack==0.11
    - terminado==0.18.1
    - terminaltables==3.1.10
    - thop==0.1.1-2209072238
    - threadpoolctl==3.4.0
    - tinycss2==1.2.1
    - toml==0.10.2
    - torch==2.2.2
    - torchpack==0.3.1
    - torchvision==0.17.2
    - tornado==6.4
    - tqdm==4.64.0
    - traitlets==5.14.2
    - trimesh==4.3.1
    - triton==2.2.0
    - types-python-dateutil==2.9.0.20240316
    - tzdata==2024.1
    - ultralytics==8.2.70
    - ultralytics-thop==2.0.0
    - uri-template==1.3.0
    - urllib3==1.26.19
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - werkzeug==3.0.2
    - widgetsnbextension==4.0.10
    - yacs==0.1.8
    - yapf==0.40.1
    - yolov5==7.0.13
    - zipp==3.18.1
prefix: /home/jingxiong/anaconda3/envs/bevfusion
