name: dqtrack
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=hb98b00a_13
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.6.1=py38h06a4308_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - huggingface_hub=0.24.6=py38h06a4308_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=14.1.0=h77fa898_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpi=1.0=openmpi
  - mpi4py=3.0.3=py38hd0bea5a_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openmpi=4.0.2=hb1b8bf9_1
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=py38h06a4308_0
  - pillow=8.4.0=py38h5aabda8_0
  - pip=24.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py38h06a4308_0
  - safetensors=0.4.5=py38ha89cbab_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - timm=1.0.11=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.10.1=py38_cu113
  - torchvision=0.11.2=py38_cu113
  - tqdm=4.66.4=py38h2f386ee_0
  - typing-extensions=4.11.0=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - black==24.8.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - click==8.1.8
      - cycler==0.12.1
      - cython==3.0.11
      - debugpy==1.8.2
      - decorator==5.1.1
      - descartes==1.1.0
      - exceptiongroup==1.2.2
      - fire==0.6.0
      - flake8==7.1.1
      - fonttools==4.53.1
      - google-auth==2.32.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.65.1
      - h5py==3.11.0
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - llvmlite==0.36.0
      - loguru==0.7.2
      - lyft-dataset-sdk==0.0.8
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - mccabe==0.7.0
      - mmcv==1.5.0
      - mmcv-full==1.5.0
      - mmdet==2.24.0
      - mmsegmentation==0.20.0
      - motmetrics==1.1.3
      - msgpack==1.0.8
      - msgpack-numpy==0.4.8
      - multimethod==1.10
      - mypy-extensions==1.0.0
      - narwhals==1.25.0
      - networkx==2.2
      - numba==0.53.0
      - numpy==1.22.3
      - nuscenes-devkit==1.1.11
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - pandas==2.0.3
      - pathspec==0.12.1
      - platformdirs==4.2.2
      - plotly==6.0.0
      - pluggy==1.5.0
      - plyfile==1.0.3
      - prefetch-generator==1.0.3
      - prettytable==3.11.0
      - protobuf==5.27.2
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pyflakes==3.2.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - setuptools==59.5.0
      - shapely==1.8.5.post1
      - six==1.16.0
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorpack==0.11
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - toml==0.10.2
      - tomli==2.0.1
      - torchpack==0.3.1
      - trimesh==2.35.39
      - tzdata==2024.1
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - yacs==0.1.8
      - yapf==0.40.1
      - zipp==3.20.2
prefix: /home/jmeng18/.conda/envs/dqtrack
